name: dayme_test_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.12
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Mariupol
      fonts:
        - asset: assets/fonts/Mariupol-Regular.ttf
        - asset: assets/fonts/Mariupol-Bold.ttf
        - asset: assets/fonts/Mariupol-Medium.ttf
        - asset: assets/fonts/MariupolSymbols.ttf
