name: dayme_test_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Mariupol
      fonts:
        - asset: assets/fonts/Mariupol-Regular.ttf
        - asset: assets/fonts/Mariupol-Bold.ttf
        - asset: assets/fonts/Mariupol-Medium.ttf
        - asset: assets/fonts/MariupolSymbols.ttf